### ISSUE TITLE
Handle UNCHANGEABLE inside string

### ISSUE THREAD

**Issue by sakopzon** [sakopzon/Compilation#7]
For example:
`":"`
should go to
`<str,:>`
#5 is parent issue

**Comment by YoavGaudin** [comment]
I changed {ANY} to (.*) in the STRING definition

**Comment by YoavGaudin** [comment]
### <write>(<str,"This is a:\n">);  // this is wrong because it has the "" showing

---

### <write>(<str,This is a:\n>);

**Comment by YoavGaudin** [comment]
Fixed in function showToken
